// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_MXFP4);

#ifdef GGML_CUDA_HAS_BLACKWELL_TARGET
DECL_MMQ_CASE_W4A4(GGML_TYPE_MXFP4);
#endif // GGML_CUDA_HAS_BLACKWELL_TARGET
