/* Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe. */
/* b-posit8 W8A8 exact-quire type: three checks through the REGISTERED type traits
 * (from_float + vec_dot + to_float), i.e. the path ggml's mul_mat uses.
 *   1. dispatch: vec_dot agrees with the dequantized double dot for streaming K;
 *   2. golden vectors: 64 single-block cases whose exact 256-bit quire result was computed
 *      by an independent rational-arithmetic reference (tests/test-bposit8-quire-golden.h,
 *      generated by test-bposit8-quire-golden-gen.py) — vec_dot must return exactly the
 *      float readout of that quire, including the catastrophic-cancellation cases;
 *   3. order independence: the same operands summed in permuted block orders give
 *      bit-identical float results (the property float accumulation does not have). */
#include "ggml.h"
#include "ggml-cpu.h"
/* the exact W8A8 quire dot (the deterministic profile's vec_dot; the type's default vec_dot uses bf16 activations) */
void ggml_vec_dot_bposit8_bposit8(int n, float * s, size_t bs, const void * vx, size_t bx, const void * vy, size_t by, int nrc);
#include "test-bposit8-quire-golden.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

static unsigned long long st = 0x2026072207ULL;
static float frand(void) { /* deterministic LCG in [-2,2) */
    st = st * 6364136223846793005ULL + 1442695040888963407ULL;
    return ((float)((st >> 33) & 0xFFFFF) / (float)0x80000) * 2.0f - 2.0f;
}

/* readout of a signed 256-bit quire (radix at BP8_QUIRE_FRAC_BITS) to float, one rounding:
 * limbs -> double (top-down) -> float, the same readout the kernel performs. */
static float quire_to_float(const uint32_t l[8]) {
    uint32_t m[8];
    memcpy(m, l, sizeof(m));
    int neg = (m[7] >> 31) & 1;
    if (neg) {
        uint64_t carry = 1;
        for (int i = 0; i < 8; i++) { uint64_t s = (uint64_t)(~m[i]) + carry; m[i] = (uint32_t)s; carry = s >> 32; }
    }
    double v = 0.0;
    for (int i = 7; i >= 0; i--) v = v * 4294967296.0 + (double)m[i];
    v = ldexp(v, -BP8_QUIRE_FRAC_BITS);
    return (float)(neg ? -v : v);
}

static uint32_t f2u(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

int main(void) {
    const enum ggml_type T = GGML_TYPE_BPOSIT8;
    const struct ggml_type_traits     * tt  = ggml_get_type_traits(T);
    const struct ggml_type_traits_cpu * ttc = ggml_get_type_traits_cpu(T);
    if (!ttc || !ttc->vec_dot || !ttc->from_float || !tt || !tt->to_float) {
        printf("FAIL: BPOSIT8 type traits not registered\n");
        return 1;
    }
    printf("registration OK: name=%s blck=%d size=%zu vec_dot_type=%d\n",
           tt->type_name, (int)ggml_blck_size(T), ggml_type_size(T), (int)ttc->vec_dot_type);
    const int qk = ggml_blck_size(T);
    const size_t bs = ggml_type_size(T);
    int fails = 0;

    /* 1. dispatch vs dequantized double dot */
    for (int trial = 0; trial < 8; trial++) {
        const int nb = 1 + trial;
        const int n  = nb * qk;
        float *x = malloc(n*sizeof(float)), *y = malloc(n*sizeof(float));
        for (int i = 0; i < n; i++) { x[i] = frand(); y[i] = frand(); }
        void *qx = malloc(nb*bs), *qy = malloc(nb*bs);
        ttc->from_float(x, qx, n);
        ttc->from_float(y, qy, n);
        float s = 0.0f;
        ggml_vec_dot_bposit8_bposit8(n, &s, 0, qx, 0, qy, 0, 1);
        float *dx = malloc(n*sizeof(float)), *dy = malloc(n*sizeof(float));
        tt->to_float(qx, dx, n);
        tt->to_float(qy, dy, n);
        double ref = 0.0;
        for (int i = 0; i < n; i++) ref += (double)dx[i]*(double)dy[i];
        double denom = fabs(ref) > 1e-9 ? fabs(ref) : 1.0;
        double rel = fabs((double)s - ref) / denom;
        int ok = rel < 1e-5;
        if (!ok) fails++;
        printf("  dispatch nb=%d n=%4d vec_dot=%.7g dequant-dot=%.7g rel=%.2e %s\n", nb, n, (double) s, (double) ref, rel, ok ? "ok" : "FAIL");
        free(x); free(y); free(qx); free(qy); free(dx); free(dy);
    }

    /* 2. golden vectors: rebuild the two blocks from the case and compare vec_dot's float
     *    with the float readout of the reference quire (exact equality of the bits). */
    int gold_ok = 0;
    for (int c = 0; c < BP8_NCASES; c++) {
        const bp8_case_t *tc = &BP8_CASES[c];
        uint8_t bx[1 + BP8_QK], by[1 + BP8_QK];
        bx[0] = (uint8_t)(int8_t)tc->sx; memcpy(bx + 1, tc->xs, BP8_QK);
        by[0] = (uint8_t)(int8_t)tc->sy; memcpy(by + 1, tc->ys, BP8_QK);
        float s = 0.0f;
        ggml_vec_dot_bposit8_bposit8(BP8_QK, &s, 0, bx, 0, by, 0, 1);
        float want = quire_to_float(tc->golden);
        if (f2u(s) == f2u(want)) gold_ok++;
        else { fails++; printf("  golden case %d: vec_dot %08x (%.9g) vs reference %08x (%.9g) FAIL\n", c, f2u(s), (double) s, f2u(want), (double) want); }
    }
    printf("  golden vectors: %d/%d bit-exact\n", gold_ok, BP8_NCASES);

    /* 3. order independence: permute the block order of both operands the same way */
    {
        const int nb = 16, n = nb * qk;
        float *x = malloc(n*sizeof(float)), *y = malloc(n*sizeof(float));
        for (int i = 0; i < n; i++) { x[i] = frand() * (i % 7 == 0 ? 64.0f : 1.0f); y[i] = frand(); }
        uint8_t *qx = malloc(nb*bs), *qy = malloc(nb*bs), *px = malloc(nb*bs), *py = malloc(nb*bs);
        ttc->from_float(x, qx, n);
        ttc->from_float(y, qy, n);
        float base = 0.0f;
        ggml_vec_dot_bposit8_bposit8(n, &base, 0, qx, 0, qy, 0, 1);
        int perm[16], same = 0, trials = 32;
        for (int t = 0; t < trials; t++) {
            for (int i = 0; i < nb; i++) perm[i] = i;
            for (int i = nb - 1; i > 0; i--) { st = st * 6364136223846793005ULL + 1442695040888963407ULL; int j = (int)((st >> 33) % (unsigned)(i + 1)); int tmp = perm[i]; perm[i] = perm[j]; perm[j] = tmp; }
            for (int i = 0; i < nb; i++) { memcpy(px + i*bs, qx + perm[i]*bs, bs); memcpy(py + i*bs, qy + perm[i]*bs, bs); }
            float s = 0.0f;
            ggml_vec_dot_bposit8_bposit8(n, &s, 0, px, 0, py, 0, 1);
            if (f2u(s) == f2u(base)) same++;
        }
        printf("  order independence: %d/%d block permutations bit-identical (%.9g)\n", same, trials, (double) base);
        if (same != trials) fails++;
        free(x); free(y); free(qx); free(qy); free(px); free(py);
    }

    printf(fails ? "== bposit8: %d FAILURE(S) ==\n" : "== bposit8 registered vec_dot: ALL OK ==\n", fails);
    return fails ? 1 : 0;
}
