if (NOT DEFINED GGML_HRX_BUNDLE_SOURCES OR NOT DEFINED GGML_HRX_BUNDLE_DESTINATION)
    message(FATAL_ERROR "HRX bundle copy requires sources and destination")
endif()

foreach(GGML_HRX_BUNDLE_SOURCE IN LISTS GGML_HRX_BUNDLE_SOURCES)
    get_filename_component(GGML_HRX_BUNDLE_NAME "${GGML_HRX_BUNDLE_SOURCE}" NAME)
    set(GGML_HRX_BUNDLE_DEST "${GGML_HRX_BUNDLE_DESTINATION}/${GGML_HRX_BUNDLE_NAME}")
    if (IS_SYMLINK "${GGML_HRX_BUNDLE_SOURCE}")
        if (NOT EXISTS "${GGML_HRX_BUNDLE_SOURCE}")
            message(FATAL_ERROR "HRX bundle source is a broken symlink: ${GGML_HRX_BUNDLE_SOURCE}")
        endif()
        file(READ_SYMLINK "${GGML_HRX_BUNDLE_SOURCE}" GGML_HRX_BUNDLE_LINK_TARGET)
    elseif (EXISTS "${GGML_HRX_BUNDLE_SOURCE}")
        if (IS_DIRECTORY "${GGML_HRX_BUNDLE_SOURCE}")
            message(FATAL_ERROR "HRX bundle source is not a regular file: ${GGML_HRX_BUNDLE_SOURCE}")
        endif()
    else()
        message(FATAL_ERROR "HRX bundle source no longer exists: ${GGML_HRX_BUNDLE_SOURCE}")
    endif()

    get_filename_component(GGML_HRX_BUNDLE_SOURCE_ABSOLUTE "${GGML_HRX_BUNDLE_SOURCE}" ABSOLUTE)
    get_filename_component(GGML_HRX_BUNDLE_DEST_ABSOLUTE "${GGML_HRX_BUNDLE_DEST}" ABSOLUTE)
    if ("${GGML_HRX_BUNDLE_SOURCE_ABSOLUTE}" STREQUAL "${GGML_HRX_BUNDLE_DEST_ABSOLUTE}")
        continue()
    endif()

    file(REMOVE "${GGML_HRX_BUNDLE_DEST}")
    if (IS_SYMLINK "${GGML_HRX_BUNDLE_SOURCE}")
        file(CREATE_LINK "${GGML_HRX_BUNDLE_LINK_TARGET}" "${GGML_HRX_BUNDLE_DEST}" SYMBOLIC)
    else()
        file(COPY "${GGML_HRX_BUNDLE_SOURCE}" DESTINATION "${GGML_HRX_BUNDLE_DESTINATION}")
    endif()
endforeach()
